import fs from 'node:fs';
import path from 'node:path';
const L=JSON.parse(fs.readFileSync('src/locales.json'));
const C=JSON.parse(fs.readFileSync('src/config.json'));
const origin=(process.env.SITE_ORIGIN||C.origin||'').replace(/\/$/,'');
const basePath=origin?new URL(origin).pathname.replace(/\/$/,''):'';
const indexable=!!origin&&(process.env.SITE_INDEXABLE==='true'||C.indexable);
const e=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const lines=s=>e(s).replaceAll('\n','<br>');
const langs=Object.keys(L), names={en:'English',fr:'Français',es:'Español',nl:'Nederlands',de:'Deutsch',pt:'Português'};
const routes={};for(const [l,t] of Object.entries(L)){routes[l]={home:l==='en'?'/':`/${l}/${t.slugs.home}/`,guide:`/${l}/${t.slugs.guide}/`,payment:`/${l}/${t.slugs.payment}/`,privacy:`/${l}/${({en:'privacy',fr:'confidentialite',es:'privacidad',nl:'privacy',de:'datenschutz',pt:'privacidade'})[l]}/`};t.residences.items.forEach((v,i)=>routes[l]['r'+i]=`/${l}/${t.slugs.residences}/${v.slug}/`)}
const num=(n,l)=>new Intl.NumberFormat(l,{maximumFractionDigits:0}).format(n);
const money=(n,l,cur='AED')=>`${cur} ${num(cur==='USD'?Math.round(n/C.aedPerUsd):n,l)}`;
const range=(a,b,l,cur='AED')=>a===b?money(a,l,cur):`${money(a,l,cur)}–${num(cur==='USD'?Math.round(b/C.aedPerUsd):b,l)}`;
const manifest=JSON.parse(fs.readFileSync('dist/assets/assets-manifest.json'));
function pic(name,alt,hero=false,cls=''){return `<picture><source media="(max-width: 720px)" srcset="/assets/${name}-800.webp"><img class="${cls}" src="/assets/${name}.webp" width="1920" height="1080" alt="${e(alt)}" ${hero?'fetchpriority="high" loading="eager"':'loading="lazy" decoding="async"'}></picture>`}
const arrow = '<svg class="icon-arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="22" height="22" fill="none" aria-hidden="true" focusable="false"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const downArrow = arrow.replace('icon-arrow','icon-arrow icon-down');
const menuIcon = '<svg class="icon-menu" viewBox="0 0 24 24" width="24" height="24" fill="none" aria-hidden="true" focusable="false"><path class="menu-line-top" d="M4 8h16"/><path class="menu-line-bottom" d="M4 16h16"/></svg>';
const btn=(text,url='#contact',light=false)=>`<a class="btn ${light?'btn-light':''}" href="${url}">${e(text)}<span aria-hidden="true">${arrow}</span></a>`;
const link=(text,url)=>`<a class="text-link" href="${url}">${e(text)}<span aria-hidden="true">${arrow}</span></a>`;
function header(l,key){let t=L[l],r=routes[l];const nav=`<a href="${r.home}#residences">${e(t.nav.residences)}</a><a href="${r.plans}">${e(X[l].plansLabel)}</a><a href="${r.home}#lifestyle">${e(t.nav.lifestyle)}</a><a href="${r.home}#prices">${e(X[l].prices)}</a>`;return `<a class="skip" href="#main">${e(t.ui.discover)}</a><header class="topbar"><a class="brand" href="${r.home}"><img src="/assets/logo-dark.svg" width="166" height="48" alt="${e(t.alt.logo)}"></a><nav class="navlinks" aria-label="${e(t.footer.explore)}">${nav}</nav><div class="header-actions"><details class="language-picker group relative" data-language-picker><summary class="flex min-h-11 cursor-pointer list-none items-center gap-2 rounded-full border border-[#c8ccbb] px-3 text-[11px] font-medium tracking-widest transition-colors hover:bg-[#e7e1d5] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#535d43] [&::-webkit-details-marker]:hidden" aria-label="${e(t.nav.language)}: ${names[l]}"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" aria-hidden="true"><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></svg><span>${l.toUpperCase()}</span><svg class="h-3 w-3 transition-transform duration-300 group-open:rotate-180 motion-reduce:transition-none" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m4 6 4 4 4-4"/></svg></summary><nav class="language-panel absolute right-0 z-50 mt-3 w-52 max-w-[calc(100vw-3rem)] rounded-2xl border border-[#c8ccbb] bg-[#f4f1e9] p-2 text-[#333a2d] shadow-xl" aria-label="${e(t.nav.language)}">${langs.map(x=>`<a class="flex min-h-11 items-center justify-between gap-5 rounded-xl px-3 py-3 text-sm transition-colors hover:bg-[#e7e1d5] focus-visible:bg-[#e7e1d5] ${x===l?'bg-[#e7e1d5] font-semibold':''}" href="${routes[x][key]}" lang="${x}" ${x===l?'aria-current="page"':''}><span>${names[x]}</span>${x===l?'<svg class="h-4 w-4" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m4 10 4 4 8-8"/></svg>':`<span class="text-[10px] tracking-widest opacity-50">${x.toUpperCase()}</span>`}</a>`).join('')}</nav></details><a class="nav-cta" href="#contact">${e(t.nav.contact)} ${arrow}</a><button class="menu-button" aria-label="${e(t.nav.menu)}" aria-expanded="false" aria-controls="mobile-nav">${menuIcon}</button></div><nav class="mobile-nav" id="mobile-nav" aria-label="${e(t.footer.explore)}">${nav}<a href="#contact">${e(t.nav.contact)}</a></nav></header>`}
function contact(t,l){return `<section class="contact section wrap" id="contact"><div><p class="eyebrow">${e(t.contact.eyebrow)}</p><h2>${lines(t.contact.title)}</h2><p class="body-copy">${e(t.contact.text)}</p><p class="notice">${e(t.contact.reassurance)}</p></div><div class="form-shell"><iframe data-tally-src="https://tally.so/embed/${C.tallyId}?alignLeft=1&amp;hideTitle=1&amp;transparentBackground=1&amp;dynamicHeight=1" loading="lazy" width="100%" height="448" title="${e(t.ui.formTitle)}"></iframe><p><a class="underline" href="${routes[l].privacy}">${e(t.footer.privacy)}</a></p></div></section>`}
function footer(t,l,key){const r=routes[l];return `<footer class="footer"><div class="footer-top"><div><a class="brand" href="${r.home}"><img src="/assets/logo-light.svg" width="210" height="65" alt="${e(t.alt.logo)}"></a><p>${e(t.footer.description)}</p></div><div><h3>${e(t.footer.explore)}</h3>${t.residences.items.map((v,i)=>`<a href="${r['r'+i]}">${e(v.name)}</a>`).join('')}<a href="${r.home}#lifestyle">${e(t.nav.lifestyle)}</a><a href="${r.home}#location">${e(t.nav.location)}</a><a href="${r.plans}">${e(X[l].plansLabel)}</a></div><div><h3>${e(t.footer.investment)}</h3><a href="${r.guide}">${e(t.ui.readGuide)}</a><a href="${r.payment}">${e(t.payment.cta)}</a><a href="${r.home}#visa">Investor Visa & Golden Visa</a><a href="${r.home}#faq">FAQ</a><a href="${r.privacy}">${e(t.footer.privacy)}</a></div></div><div class="flex flex-wrap gap-x-7 gap-y-2 mb-8">${langs.map(x=>`<a hreflang="${x}" lang="${x}" href="${routes[x][key]}">${names[x]}</a>`).join('')}</div><div class="footer-bottom"><span>© 2026 SAMANA South Haven 2. ${e(t.footer.copyright)}</span><span>${e(t.ui.rendering)}<br>${e(t.pricing.availabilityNote)}</span></div><div class="footer-word" aria-hidden="true">${e(t.contact.title.replaceAll("\n"," "))}</div></footer><a class="sticky-cta btn" href="#contact">${e(t.contact.cta)} <span aria-hidden="true">${arrow}</span></a>`}
function faq(t){return `<section class="faq section wrap" id="faq"><div><p class="eyebrow">${e(t.faq.eyebrow)}</p><h2>${lines(t.faq.title)}</h2></div><div>${t.faq.items.map(v=>`<details><summary>${e(v.q)}</summary><p>${e(v.a)}</p></details>`).join('')}</div></section>`}
function visas(t){return `<section class="section wrap" id="visa"><p class="eyebrow mb-7">${e(t.visa.eyebrow)}</p><h2>${lines(t.visa.title)}</h2><p class="body-copy mt-8">${e(t.visa.text)}</p><div class="visa-grid"><article class="visa-card"><h3>Investor Visa</h3><p>${e(t.visa.investor)}</p></article><article class="visa-card"><h3>Golden Visa</h3><p>${e(t.visa.golden)}</p></article></div><p class="notice">${e(t.visa.note)}</p></section>`}
function subhero(t,l,key,title,description){return `<section class="subhero"><div class="breadcrumb"><a href="${routes[l].home}">SAMANA South Haven 2</a><span>/</span><span>${e(key==='guide'?t.nav.invest:key==='payment'?t.footer.investment:key==='privacy'?t.footer.privacy:t.nav.residences)}</span></div><p class="eyebrow">DUBAI SOUTH · SAMANA SOUTH HAVEN 2</p><h1>${lines(title)}</h1><p>${e(description)}</p></section>`}
function pricing(t,l,i){let p=t.pricing;return `<div class="table-wrap">${i===0?`<table><caption class="sr-only">${e(p.title)}</caption><thead><tr><th>${e(p.floor)}</th><th>AED</th><th>USD ≈</th></tr></thead><tbody>${C.studioFloors.map(v=>`<tr><td>${e(p.floor)} ${v.floor}</td><td>${range(v.min,v.max,l)}</td><td>${range(v.min,v.max,l,'USD')}</td></tr>`).join('')}</tbody></table><p class="notice">${e(p.parkingStudio)}</p>`:i===2?`<table><tbody><tr><th>${e(p.range)}</th><td>${range(C.twoBed.min,C.twoBed.max,l)}<br>≈ ${range(C.twoBed.min,C.twoBed.max,l,'USD')}</td></tr><tr><th>${e(p.units)}</th><td>${C.twoBed.units.join(' · ')}</td></tr><tr><th>${e(p.area)}</th><td>≈ 1,059–1,085 sq. ft. / 98.4–100.8 m²</td></tr><tr><th>${e(p.communityView)}</th><td>${e(p.parkingTwo)}</td></tr></tbody></table>`:`<p>${e(t.ui.onRequest)}</p>`}</div><p class="notice">${e(p.usdNote)} ${e(p.availabilityNote)} ${e(p.sourceNote)}</p>`}
function guide(t,l){return `${subhero(t,l,'guide',t.guide.title,t.guide.eyebrow)}${pic('aerial',t.alt.architecture,false,'wide-image')}<article class="article">${t.guide.paragraphs.map((p,i)=>`<p>${e(p)}</p>${i===0?`<h2>${e(t.pricing.title)}</h2>${pricing(t,l,0)}`:''}`).join('')}${btn(t.guide.cta)}</article>${visas(t)}${faq(t)}`}
function payment(t,l){return `${subhero(t,l,'payment',t.payment.title,t.payment.text)}<article class="article"><div class="steps">${t.payment.steps.map((v,i)=>`<article><p class="eyebrow">0${i+1}</p><h3>${e(v)}</h3></article>`).join('')}</div><h2>${e(t.ui.studio)}</h2>${pricing(t,l,0)}<h2>${e(t.ui.twoBed)}</h2>${pricing(t,l,2)}<p>${e(t.ui.oneBed)}: ${e(t.ui.onRequest)}.</p>${btn(t.payment.cta)}</article>`}
function privacy(t,l){return `${subhero(t,l,'privacy',t.footer.privacy,t.footer.description)}<article class="article"><p>${e(t.footer.privacyText)}</p><h2>${e(t.footer.disclaimer)}</h2><p>${e(t.footer.disclaimerText)}</p><p>${e(t.visa.note)}</p><p>${e(t.pricing.usdNote)}</p><h2>${e(t.footer.sources)}</h2><p>${e(t.footer.brochureSource)}</p><p>Central Bank of the UAE · Dubai Land Department</p></article>`}
const X=JSON.parse(fs.readFileSync('src/experience.json'));
const P=JSON.parse(fs.readFileSync('src/plans.json'));
function planName(x,p){return [x.studio,x.one,x.two][p.group]+(p.variant?` · ${x.type} ${p.variant}`:'')}
function planLink(src,label,title,cls=''){return `<a class="${cls}" href="/assets/${src}.webp" data-plan data-plan-title="${e(title)}">${e(label)} ${arrow}</a>`}
function planCards(t,l,group=null){const x=X[l],plans=group===null?P:P.filter(p=>p.group===group);return `<div class="plan-gallery">${plans.map(p=>`<article class="layout-card" data-plan-group="${p.group}" id="layout-${p.id}"><a class="layout-preview" href="/assets/${p.id}-layout.webp" data-plan data-plan-title="${e(planName(x,p))}"><img src="/assets/${p.id}-layout.webp" alt="${e(x.layout+' · '+planName(x,p))}" width="${manifest.find(a=>a.file===p.id+'-layout.webp').width}" height="${manifest.find(a=>a.file===p.id+'-layout.webp').height}" loading="lazy"><span>${e(x.enlarge)} ${arrow}</span></a><div class="layout-info"><p class="eyebrow">${e(x.page)} ${p.page}</p><h3>${e(planName(x,p))}</h3><p>${e([x.studioFeatures,x.oneFeatures,x.twoFeatures][p.group])}</p><dl><div><dt>${e(x.floors)}</dt><dd>${p.floors}</dd></div><div><dt>${e(x.area)}</dt><dd>${p.group===2?'≈ 1,059–1,085 sq. ft.':e(x.request)}</dd></div></dl><div class="plan-links">${planLink(p.id+'-keyplan',x.keyplan,planName(x,p)+' · '+x.keyplan)}${planLink(p.sheet,x.sheet,planName(x,p)+' · '+x.sheet)}</div></div></article>`).join('')}</div><p class="notice">${e(x.planNote)} ${e(x.availabilityNote)}</p>`}
function amenityPlans(t,l){const x=X[l];return `<section class="section wrap amenity-plans" id="amenity-plans"><div class="feature-heading"><div><p class="eyebrow">${e(x.amenitiesPlans)}</p><h2>${e(x.firstAmenities)}.<br>${e(x.roofAmenities)}.</h2></div><p>${e(x.lifestyleText)}</p></div><div class="amenity-plan-grid">${[['amenities-first-plan',x.firstAmenities,x.poolFeatures+' · '+x.familyFeatures,24],['amenities-roof-plan',x.roofAmenities,x.roofFeatures,23]].map(([name,title,copy,page])=>`<article><a href="/assets/${name}.webp" data-plan data-plan-title="${e(title)}"><img src="/assets/${name}.webp" width="2400" height="1697" alt="${e(title)}" loading="lazy"></a><div><p class="eyebrow">${e(x.page)} ${page}</p><h3>${e(title)}</h3><p>${e(copy)}</p>${planLink(name,x.enlarge,title,'text-link')}</div></article>`).join('')}</div></section>`}
function planDialog(l){const x=X[l];return `<dialog class="plan-dialog" aria-labelledby="plan-dialog-title"><div class="dialog-card"><header><h2 id="plan-dialog-title">${e(x.gallery)}</h2><button type="button" data-plan-close aria-label="${e(x.close)}"><svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m6 6 12 12M6 18 18 6"/></svg></button></header><div class="plan-toolbar"><button type="button" data-plan-zoom="out" aria-label="${e(x.zoomOut)}">−</button><button type="button" data-plan-zoom="in" aria-label="${e(x.zoomIn)}">+</button><button type="button" data-plan-zoom="fit">${e(x.fit)}</button><a data-plan-download download>${e(x.download)}</a></div><div class="plan-stage"><img data-plan-image alt=""></div><p class="dialog-note">${e(x.planNote)}</p></div></dialog>`}
function residences(t,l){const x=X[l];return `<section class="section wrap residences-section" id="residences"><div class="feature-heading"><div><p class="eyebrow">${e(x.glance)}</p><h2>${lines(x.categoriesTitle)}</h2></div><p>${e(x.categoriesText)}</p></div><div class="category-grid">${[P[0],P[1],P[5]].map((p,i)=>`<article class="category-card"><a class="category-visual" href="${routes[l]['r'+i]}"><span class="eyebrow">0${i+1} / ${e(x.plans)} ${i===1?'× 4':'× 1'}</span><img src="/assets/${p.id}-layout.webp" width="${manifest.find(a=>a.file===p.id+'-layout.webp').width}" height="${manifest.find(a=>a.file===p.id+'-layout.webp').height}" alt="${e(planName(x,p))}" loading="lazy"></a><div class="category-copy"><h3>${e([x.studio,x.one,x.two][i])}</h3><p>${e([x.studioFeatures,x.oneFeatures,x.twoFeatures][i])}</p><div class="category-price"><span>${e(i===1?x.starting:t.pricing.from)}</span><strong>${i===1?e(x.request):money(i===0?C.studioFloors[0].min:C.twoBed.min,l)}</strong>${i===1?'':`<small>≈ ${money(i===0?C.studioFloors[0].min:C.twoBed.min,l,'USD')}</small>`}</div>${link(x.explore,routes[l]['r'+i])}</div></article>`).join('')}</div><div class="section-tail">${btn(x.allPlans,routes[l].plans)}<p>${e(x.variantNote)} ${e(t.pricing.availabilityNote)}</p></div></section>`}
function home(t,l){const x=X[l],r=routes[l];return `<section class="hero clear-hero">${pic('hero',t.alt.hero,true)}<div class="hero-copy"><p class="eyebrow">SAMANA SOUTH HAVEN 2 · DUBAI SOUTH</p><h1>${lines(x.heroTitle)}</h1><p class="hero-description">${e(x.heroText)}</p><div class="hero-bottom"><div class="hero-price"><span class="hero-price-label">${e(x.studio)} · ${e(t.pricing.from)}</span><div class="hero-price-main"><span class="hero-price-currency">AED</span><strong>${num(644000,l)}</strong></div><span class="hero-price-usd">≈ ${money(644000,l,'USD')}</span></div><div class="hero-cta-pair">${btn(x.explore,'#residences',true)}${link(x.prices,'#prices')}</div></div><p class="hero-rendering">${e(t.ui.rendering)}</p></div></section><div class="quick-facts wrap" id="project"><div><span>${e(x.location)}</span><strong>${e(x.developer)}</strong></div><div><span>${e(x.categoryCount)}</span><strong>${e(x.layoutCount)}</strong></div><div><span>${e(x.sharedPools)}</span><strong>${e(t.nav.lifestyle)}</strong></div><div><span>${e(x.handover)}</span><strong>${e(x.confirm)}</strong></div></div><nav class="section-nav wrap" aria-label="${e(x.essential)}"><a href="#residences">${e(x.explore)}</a><a href="#prices">${e(x.prices)}</a><a href="#lifestyle">${e(t.nav.lifestyle)}</a><a href="#location">${e(t.nav.location)}</a><a href="#faq">FAQ</a></nav>
${residences(t,l)}
<section class="section wrap price-section" id="prices"><div class="feature-heading"><div><p class="eyebrow">${e(x.essential)}</p><h2>${e(x.prices)}.</h2></div><p>${e(x.essentialText)}</p></div><div class="price-grid"><article><h3>${e(x.studiosFloors)}</h3>${pricing(t,l,0)}</article><article><h3>${e(x.twoTitle)}</h3>${pricing(t,l,2)}</article></div><div class="payment-callout"><div><h3>${e(x.paymentTitle)}</h3><p>${e(x.paymentText)}</p></div>${btn(t.payment.cta,r.payment)}</div></section>
<section class="split wrap section"><div class="reveal">${pic('night',t.alt.architecture)}<p class="caption">${e(t.ui.rendering)}</p></div><div class="reveal"><p class="eyebrow">${e(t.architecture.eyebrow)}</p><h2>${lines(t.architecture.title)}</h2><p class="body-copy">${e(t.architecture.text)}</p>${link(x.allPlans,r.plans)}</div></section>
<section class="olive section" id="lifestyle"><div class="feature-heading wrap"><div><p class="eyebrow">${e(t.amenities.eyebrow)}</p><h2>${e(x.lifestyleTitle)}</h2></div><p>${e(x.lifestyleText)}</p></div><div class="panorama">${pic('pool',t.alt.pool)}</div><div class="wrap"><div class="amenity-list expanded-amenities">${[[x.poolFamily,x.poolFeatures,x.familyFeatures],[x.fitness,x.fitnessFeatures,x.roofFeatures],[x.work,x.workFeatures,x.amenityExtra]].map((v,i)=>`<article><span>0${i+1}</span><h3>${e(v[0])}</h3><p>${e(v[1])}</p><p>${e(v[2])}</p></article>`).join('')}</div><div class="amenity-photo-grid">${['kids-pool','gym','lobby'].map((n,i)=>`<figure>${pic(n,[x.poolFamily,x.fitness,x.lobby][i])}<figcaption>${e([x.poolFamily,x.fitness,x.lobby][i])}</figcaption></figure>`).join('')}</div>${link(x.amenitiesPlans,'#amenity-plans')}</div></section>
${amenityPlans(t,l)}
<section class="section wrap interior-section"><div class="feature-heading"><div><p class="eyebrow">${e(x.interiors)}</p><h2>${e(x.interiorsTitle)}</h2></div><p>${e(t.ui.rendering)}</p></div><div class="interior-grid">${[['dining',x.living],['bedroom',x.bedroom],['bathroom',x.bathroom]].map(([n,label])=>`<figure>${pic(n,label)}<figcaption>${e(label)}</figcaption></figure>`).join('')}</div></section>
<section class="split reverse wrap section" id="location"><div><p class="eyebrow">${e(t.location.eyebrow)}</p><h2>${lines(t.location.title)}</h2><p class="body-copy">${e(t.location.text)}</p><div class="destinations">${t.location.landmarks.map(v=>`<span>${e(v)}</span>`).join('')}</div><p class="notice">${e(t.location.note)}</p>${link(t.ui.readGuide,r.guide)}</div><div><a href="/assets/location-map.webp" data-plan data-plan-title="${e(t.nav.location)} · Dubai South"><img class="location-map" src="/assets/location-map.webp" width="2000" height="1414" alt="${e(t.nav.location)} · Dubai South" loading="lazy"></a>${planLink('location-map',x.enlarge,t.nav.location+' · Dubai South','text-link')}</div></section>
<section class="section wrap purchase-section"><div class="feature-heading"><div><p class="eyebrow">${e(t.guide.eyebrow)}</p><h2>${e(x.purchaseTitle)}</h2></div>${link(t.ui.readGuide,r.guide)}</div><div class="purchase-grid">${[1,2,3].map(i=>`<article><span>0${i}</span><h3>${e(x['step'+i])}</h3><p>${e(x['step'+i+'Text'])}</p></article>`).join('')}</div></section>${visas(t)}${faq(t)}`}
function residence(t,l,i){const x=X[l],v=t.residences.items[i];return `${subhero(t,l,'r'+i,v.name,v.description)}<div class="wrap residence-overview"><div><span>${e(x.starting)}</span><strong>${i===1?e(x.request):money(i===0?644000:1314000,l)}</strong>${i===1?'':`<small>≈ ${money(i===0?644000:1314000,l,'USD')}</small>`}</div><div><span>${e(x.floors)}</span><strong>${i===2?'2–6':'1–6'}</strong></div><div><span>${e(x.area)}</span><strong>${i===2?'≈ 1,059–1,085 sq. ft.':e(x.request)}</strong></div>${btn(x.explore,'#floorplans')}</div><section class="section wrap" id="floorplans"><div class="feature-heading"><h2>${e(x.plansLabel)}.</h2><p>${e(x.categoriesText)}</p></div>${planCards(t,l,i)}</section><section class="section wrap price-section"><div class="price-detail"><div><p class="eyebrow">${e(x.prices)}</p><h2>${e(v.name)}</h2><p>${e(x.variantNote)}</p>${btn(t.ui.requestPrice)}</div><div>${pricing(t,l,i)}</div></div><div class="payment-callout"><div><h3>${e(x.paymentTitle)}</h3><p>${e(x.paymentText)}</p></div>${link(t.payment.cta,routes[l].payment)}</div></section><section class="split wrap section"><div>${pic(i===0?'living':i===1?'bedroom':'dining',t.alt.interior)}</div><div><p class="eyebrow">${e(x.interiors)}</p><h2>${e(x.interiorsTitle)}</h2><p class="body-copy">${e([x.studioFeatures,x.oneFeatures,x.twoFeatures][i])}</p>${btn(t.hero.cta)}</div></section>${residences(t,l)}${faq(t)}`}
function allPlans(t,l){const x=X[l];return `${subhero(t,l,'plans',x.plansTitle,x.plansText)}<section class="wrap section plans-hub" id="floorplans"><div class="plan-filters" aria-label="${e(x.category)}">${[x.all,x.studio,x.one,x.two].map((label,i)=>`<button type="button" data-plan-filter="${i===0?'all':i-1}" aria-pressed="${i===0}">${e(label)}</button>`).join('')}</div>${planCards(t,l)}</section>${amenityPlans(t,l)}`}

for(const l of langs)routes[l].plans=`/${l}/${X[l].plansSlug}/`;
let all=[];for(const [l,t] of Object.entries(L))for(const key of Object.keys(routes[l])){const r=routes[l][key];const pageTitle=key==='home'?t.seo.title:`${(key==='guide'?t.guide.title:key==='payment'?t.payment.cta:key==='privacy'?t.footer.privacy:key==='plans'?X[l].plansLabel:t.residences.items[+key.slice(1)].name).replaceAll('\n',' ')} | SAMANA South Haven 2`;
const description=key==='home'?t.seo.description:key==='guide'?t.guide.paragraphs[0].slice(0,170):key==='payment'?t.payment.text:key==='privacy'?t.footer.description:key==='plans'?X[l].plansText:t.residences.items[+key.slice(1)].description;
const content=key==='home'?home(t,l):key==='guide'?guide(t,l):key==='payment'?payment(t,l):key==='privacy'?privacy(t,l):key==='plans'?allPlans(t,l):residence(t,l,+key.slice(1));
let schemas=[{'@context':'https://schema.org','@type':'WebPage',name:pageTitle,description,inLanguage:l,...(origin?{url:origin+r}:{})}];if(['home','guide','r0','r1','r2'].includes(key))schemas.push({'@context':'https://schema.org','@type':'FAQPage',mainEntity:t.faq.items.map(v=>({'@type':'Question',name:v.q,acceptedAnswer:{'@type':'Answer',text:v.a}}))});
const html=`<!doctype html><html lang="${l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(pageTitle)}</title><meta name="description" content="${e(description)}"><meta name="robots" content="${indexable?'index,follow,max-image-preview:large':'noindex,follow'}"><meta name="theme-color" content="#f4f1e9"><link rel="canonical" href="${origin+r}">${langs.map(x=>`<link rel="alternate" hreflang="${x}" href="${origin+routes[x][key]}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin+routes.en[key]}"><meta property="og:type" content="website"><meta property="og:title" content="${e(pageTitle)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${origin+r}"><meta property="og:site_name" content="SAMANA South Haven 2"><meta property="og:image" content="${origin}/assets/social-hero.jpg"><meta property="og:image:secure_url" content="${origin}/assets/social-hero.jpg"><meta property="og:image:type" content="image/jpeg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${e(t.alt.hero)}"><meta property="og:locale" content="${({en:'en_US',fr:'fr_FR',es:'es_ES',nl:'nl_NL',de:'de_DE',pt:'pt_PT'})[l]}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${e(pageTitle)}"><meta name="twitter:description" content="${e(description)}"><meta name="twitter:image" content="${origin}/assets/social-hero.jpg"><meta name="twitter:image:alt" content="${e(t.alt.hero)}"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/styles.css"><script type="application/ld+json">${JSON.stringify(schemas).replaceAll('<','\\u003c')}</script><script src="/assets/app.js" defer></script></head><body>${header(l,key)}<main id="main">${content}${contact(t,l)}</main>${footer(t,l,key)}${planDialog(l)}</body></html>`;
const file=path.join('dist',r,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,basePath?html.replace(/(href|src|value|srcset)="(\/[^"]*)"/g,(_,attribute,url)=>`${attribute}="${basePath}${url}"`):html);all.push({lang:l,key,path:r,title:pageTitle});}
fs.copyFileSync('src/app.js','dist/assets/app.js');fs.writeFileSync('dist/assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" fill="#333a2d"/><text x="32" y="47" font-size="46" fill="#f4f1e9" font-family="Arial" text-anchor="middle">S</text></svg>');
fs.writeFileSync('dist/robots.txt',indexable?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
const xml=s=>e(s);fs.writeFileSync('dist/sitemap-pages.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${origin?all.map(v=>`<url><loc>${xml(origin+v.path)}</loc>${langs.map(l=>`<xhtml:link rel="alternate" hreflang="${l}" href="${xml(origin+routes[l][v.key])}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${xml(origin+routes.en[v.key])}"/></url>`).join(''):''}</urlset>`);
const imageEntries=origin?all.flatMap(v=>{
 const html=fs.readFileSync(path.join('dist',v.path,'index.html'),'utf8');
 const images=[...new Set([...html.matchAll(/<img[^>]*src="([^"]+\.webp)"/g)].map(m=>m[1]))];
 return images.length?[`<url><loc>${xml(origin+v.path)}</loc>${images.map(src=>`<image:image><image:loc>${xml(new URL(src,origin).href)}</image:loc></image:image>`).join('')}</url>`]:[];
}):[];
fs.writeFileSync('dist/sitemap-images.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">${imageEntries.join('')}</urlset>`);
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${origin?['sitemap-pages.xml','sitemap-images.xml'].map(file=>`<sitemap><loc>${xml(origin+'/'+file)}</loc></sitemap>`).join(''):''}</sitemapindex>`);
fs.writeFileSync('dist/404.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Page not found | SAMANA South Haven 2</title><meta name="robots" content="noindex,follow"><link rel="stylesheet" href="/assets/styles.css"><main class="subhero"><p>404</p><h1>Find your way home.</h1><a class="btn" href="/">SAMANA South Haven 2 ${arrow}</a></main></html>`);
if(basePath){const file='dist/404.html';fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace(/(href|src)="(\/[^"]*)"/g,(_,a,u)=>`${a}="${basePath}${u}"`));}
fs.writeFileSync('routes.json',JSON.stringify(all,null,2));console.log(`Built ${all.length} pages in ${langs.length} languages. Origin: ${origin||'not configured; local preview'}. Indexable: ${indexable}`);
