import fs from 'node:fs';
import path from 'node:path';
const L=JSON.parse(fs.readFileSync('src/locales.json'));
const C=JSON.parse(fs.readFileSync('src/config.json'));
const origin=(process.env.SITE_ORIGIN||C.origin||'').replace(/\/$/,'');
const basePath=origin?new URL(origin).pathname.replace(/\/$/,''):'';
const indexable=!!origin&&(process.env.SITE_INDEXABLE==='true'||C.indexable);
const e=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const lines=s=>e(s).replaceAll('\n','<br>');
const langs=Object.keys(L), names={en:'English',fr:'Français',es:'Español',nl:'Nederlands',de:'Deutsch',pt:'Português'};
const routes={};for(const [l,t] of Object.entries(L)){routes[l]={home:l==='en'?'/':`/${l}/${t.slugs.home}/`,guide:`/${l}/${t.slugs.guide}/`,payment:`/${l}/${t.slugs.payment}/`,privacy:`/${l}/${({en:'privacy',fr:'confidentialite',es:'privacidad',nl:'privacy',de:'datenschutz',pt:'privacidade'})[l]}/`};t.residences.items.forEach((v,i)=>routes[l]['r'+i]=`/${l}/${t.slugs.residences}/${v.slug}/`)}
const num=(n,l)=>new Intl.NumberFormat(l,{maximumFractionDigits:0}).format(n);
const money=(n,l,cur='AED')=>`${cur} ${num(cur==='USD'?Math.round(n/C.aedPerUsd):n,l)}`;
const range=(a,b,l,cur='AED')=>a===b?money(a,l,cur):`${money(a,l,cur)}–${num(cur==='USD'?Math.round(b/C.aedPerUsd):b,l)}`;
const manifest=JSON.parse(fs.readFileSync('dist/assets/assets-manifest.json'));
function pic(name,alt,hero=false,cls=''){return `<picture><source media="(max-width: 720px)" srcset="/assets/${name}-800.webp"><img class="${cls}" src="/assets/${name}.webp" width="1920" height="1080" alt="${e(alt)}" ${hero?'fetchpriority="high" loading="eager"':'loading="lazy" decoding="async"'}></picture>`}
const arrow = '<svg class="icon-arrow" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="22" height="22" fill="none" aria-hidden="true" focusable="false"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.35" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const downArrow = arrow.replace('icon-arrow','icon-arrow icon-down');
const menuIcon = '<svg class="icon-menu" viewBox="0 0 24 24" width="24" height="24" fill="none" aria-hidden="true" focusable="false"><path class="menu-line-top" d="M4 8h16"/><path class="menu-line-bottom" d="M4 16h16"/></svg>';
const btn=(text,url='#contact',light=false)=>`<a class="btn ${light?'btn-light':''}" href="${url}">${e(text)}<span aria-hidden="true">${arrow}</span></a>`;
const link=(text,url)=>`<a class="text-link" href="${url}">${e(text)}<span aria-hidden="true">${arrow}</span></a>`;
function header(l,key){let t=L[l],r=routes[l];const nav=`<a href="${r.home}#project">${e(t.nav.project)}</a><a href="${r.home}#residences">${e(t.nav.residences)}</a><a href="${r.home}#lifestyle">${e(t.nav.lifestyle)}</a><a href="${r.guide}">${e(t.nav.invest)}</a>`;return `<a class="skip" href="#main">${e(t.ui.discover)}</a><header class="topbar"><a class="brand" href="${r.home}"><img src="/assets/logo-dark.svg" width="166" height="48" alt="${e(t.alt.logo)}"></a><nav class="navlinks" aria-label="${e(t.footer.explore)}">${nav}</nav><div class="header-actions"><details class="language-picker group relative" data-language-picker><summary class="flex min-h-11 cursor-pointer list-none items-center gap-2 rounded-full border border-[#c8ccbb] px-3 text-[11px] font-medium tracking-widest transition-colors hover:bg-[#e7e1d5] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#535d43] [&::-webkit-details-marker]:hidden" aria-label="${e(t.nav.language)}: ${names[l]}"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" aria-hidden="true"><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></svg><span>${l.toUpperCase()}</span><svg class="h-3 w-3 transition-transform duration-300 group-open:rotate-180 motion-reduce:transition-none" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m4 6 4 4 4-4"/></svg></summary><nav class="language-panel absolute right-0 z-50 mt-3 w-52 max-w-[calc(100vw-3rem)] rounded-2xl border border-[#c8ccbb] bg-[#f4f1e9] p-2 text-[#333a2d] shadow-xl" aria-label="${e(t.nav.language)}">${langs.map(x=>`<a class="flex min-h-11 items-center justify-between gap-5 rounded-xl px-3 py-3 text-sm transition-colors hover:bg-[#e7e1d5] focus-visible:bg-[#e7e1d5] ${x===l?'bg-[#e7e1d5] font-semibold':''}" href="${routes[x][key]}" lang="${x}" ${x===l?'aria-current="page"':''}><span>${names[x]}</span>${x===l?'<svg class="h-4 w-4" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m4 10 4 4 8-8"/></svg>':`<span class="text-[10px] tracking-widest opacity-50">${x.toUpperCase()}</span>`}</a>`).join('')}</nav></details><a class="nav-cta" href="#contact">${e(t.nav.contact)} ${arrow}</a><button class="menu-button" aria-label="${e(t.nav.menu)}" aria-expanded="false" aria-controls="mobile-nav">${menuIcon}</button></div><nav class="mobile-nav" id="mobile-nav" aria-label="${e(t.footer.explore)}">${nav}<a href="#contact">${e(t.nav.contact)}</a></nav></header>`}
function contact(t,l){return `<section class="contact section wrap" id="contact"><div><p class="eyebrow">${e(t.contact.eyebrow)}</p><h2>${lines(t.contact.title)}</h2><p class="body-copy">${e(t.contact.text)}</p><p class="notice">${e(t.contact.reassurance)}</p></div><div class="form-shell"><iframe data-tally-src="https://tally.so/embed/${C.tallyId}?alignLeft=1&amp;hideTitle=1&amp;transparentBackground=1&amp;dynamicHeight=1" loading="lazy" width="100%" height="448" title="${e(t.ui.formTitle)}"></iframe><p><a class="underline" href="${routes[l].privacy}">${e(t.footer.privacy)}</a></p></div></section>`}
function footer(t,l,key){const r=routes[l];return `<footer class="footer"><div class="footer-top"><div><a class="brand" href="${r.home}"><img src="/assets/logo-light.svg" width="210" height="65" alt="${e(t.alt.logo)}"></a><p>${e(t.footer.description)}</p></div><div><h3>${e(t.footer.explore)}</h3>${t.residences.items.map((v,i)=>`<a href="${r['r'+i]}">${e(v.name)}</a>`).join('')}<a href="${r.home}#lifestyle">${e(t.nav.lifestyle)}</a><a href="${r.home}#location">${e(t.nav.location)}</a></div><div><h3>${e(t.footer.investment)}</h3><a href="${r.guide}">${e(t.ui.readGuide)}</a><a href="${r.payment}">${e(t.payment.cta)}</a><a href="${r.home}#visa">Investor Visa & Golden Visa</a><a href="${r.home}#faq">FAQ</a><a href="${r.privacy}">${e(t.footer.privacy)}</a></div></div><div class="flex flex-wrap gap-x-7 gap-y-2 mb-8">${langs.map(x=>`<a hreflang="${x}" lang="${x}" href="${routes[x][key]}">${names[x]}</a>`).join('')}</div><div class="footer-bottom"><span>© 2026 SAMANA South Haven 2. ${e(t.footer.copyright)}</span><span>${e(t.ui.rendering)}<br>${e(t.pricing.availabilityNote)}</span></div><div class="footer-word" aria-hidden="true">${e(t.contact.title.replaceAll("\n"," "))}</div></footer><a class="sticky-cta btn" href="#contact">${e(t.contact.cta)} <span aria-hidden="true">${arrow}</span></a>`}
function faq(t){return `<section class="faq section wrap" id="faq"><div><p class="eyebrow">${e(t.faq.eyebrow)}</p><h2>${lines(t.faq.title)}</h2></div><div>${t.faq.items.map(v=>`<details><summary>${e(v.q)}</summary><p>${e(v.a)}</p></details>`).join('')}</div></section>`}
function visas(t){return `<section class="section wrap" id="visa"><p class="eyebrow mb-7">${e(t.visa.eyebrow)}</p><h2>${lines(t.visa.title)}</h2><p class="body-copy mt-8">${e(t.visa.text)}</p><div class="visa-grid"><article class="visa-card"><h3>Investor Visa</h3><p>${e(t.visa.investor)}</p></article><article class="visa-card"><h3>Golden Visa</h3><p>${e(t.visa.golden)}</p></article></div><p class="notice">${e(t.visa.note)}</p></section>`}
function residences(t,l){return `<section class="section wrap" id="residences"><div class="feature-heading"><div><p class="eyebrow">${e(t.residences.eyebrow)}</p><h2>${lines(t.residences.title)}</h2></div><p>${e(t.residences.text)}</p></div><div class="residence-list">${t.residences.items.map((v,i)=>`<a class="residence-card" href="${routes[l]['r'+i]}"><span class="number">0${i+1}</span><div><h3>${e(v.name)}</h3><p>${e(v.description)}</p></div><div class="price">${i===1?e(t.ui.onRequest):`${e(t.pricing.from)} ${money(i===0?644000:1314000,l)}<small>≈ ${money(i===0?644000:1314000,l,'USD')}</small>`}</div><span class="circle" aria-hidden="true">${arrow}</span></a>`).join('')}</div><p class="notice">${e(t.pricing.usdNote)} ${e(t.pricing.availabilityNote)}</p></section>`}
function home(t,l){let r=routes[l];return `<section class="hero">${pic('hero',t.alt.hero,true)}<span class="vertical-note">${e(t.ui.rendering)}</span><div class="hero-copy"><p class="eyebrow">${e(t.hero.eyebrow)}</p><h1>${lines(t.hero.title)}</h1><div class="hero-bottom"><p>${e(t.hero.subtitle)}</p><div class="hero-actions"><div class="hero-price"><span class="hero-price-label">${e(t.ui.studio)} · ${e(t.pricing.from)}</span><div class="hero-price-main"><span class="hero-price-currency">AED</span><strong>${num(644000,l)}</strong></div><span class="hero-price-usd">≈ ${money(644000,l,'USD')}</span></div>${btn(t.hero.cta,'#contact',true)}</div></div><div class="hero-foot"><a href="#project">${e(t.ui.scroll)} ${downArrow}</a></div></div></section>
<section class="section wrap" id="project"><div class="intro-grid reveal"><p class="eyebrow">${e(t.intro.eyebrow)}</p><div><h2>${lines(t.intro.title)}</h2><div class="intro-bottom"><p class="body-copy">${e(t.intro.text)}</p>${link(t.ui.discover,'#residences')}</div><div class="stat-row"><div class="stat"><strong>01—02</strong><span>${e(t.ui.oneBed)} · ${e(t.ui.twoBed)}</span></div><div class="stat"><strong>644k</strong><span>AED · ${e(t.pricing.from)} · ${e(t.ui.studio)}</span></div><div class="stat"><strong>Dubai<br>South</strong><span>SAMANA Developers</span></div></div></div></div></section>
<section class="split wrap section"><div class="reveal">${pic('exterior',t.alt.architecture)}<p class="caption">01 / ${e(t.ui.rendering)}</p></div><div class="reveal"><p class="eyebrow">${e(t.architecture.eyebrow)}</p><h2>${lines(t.architecture.title)}</h2><p class="body-copy">${e(t.architecture.text)}</p>${link(t.residences.cta,'#contact')}</div></section>
<section class="olive section" id="lifestyle"><div class="feature-heading wrap reveal"><div><p class="eyebrow">${e(t.amenities.eyebrow)}</p><h2>${lines(t.amenities.title)}</h2></div><p>${e(t.amenities.text)}</p></div><div class="panorama">${pic('pool',t.alt.pool)}<div class="panorama-title">${e(t.amenities.items[0])}.</div></div><div class="wrap"><div class="amenity-list">${[[0,1,2],[3,4,8],[5,9],[6,7]].map((ids,i)=>`<article><span>0${i+1}</span><h3>${e(t.amenities.items[ids[0]])}</h3><p>${ids.slice(1).map(k=>e(t.amenities.items[k])).join('<br>')}</p></article>`).join('')}</div><p class="caption">${e(t.ui.rendering)}</p></div></section>
${residences(t,l)}<section class="gallery-two wrap"><figure>${pic('living',t.alt.interior)}<figcaption class="caption">${e(t.ui.rendering)}</figcaption></figure><figure>${pic('bedroom',t.alt.interior)}<figcaption class="caption">${e(t.ui.rendering)}</figcaption></figure></section>
<section class="split reverse wrap section" id="location"><div class="reveal"><p class="eyebrow">${e(t.location.eyebrow)}</p><h2>${lines(t.location.title)}</h2><p class="body-copy">${e(t.location.text)}</p><div class="destinations">${t.location.landmarks.map(v=>`<span>${e(v)}</span>`).join('')}</div><p class="notice">${e(t.location.note)}</p></div><div class="image-offset reveal">${pic('aerial',t.alt.architecture)}<p class="caption">${e(t.ui.rendering)}</p></div></section>
<section class="section wrap location-band guide-callout"><div><p class="eyebrow">${e(t.guide.eyebrow)}</p><h2>${lines(t.guide.title)}</h2>${btn(t.ui.readGuide,r.guide)}</div><div class="steps">${t.payment.steps.map((v,i)=>`<article><p class="eyebrow mb-3">0${i+1}</p><h3>${e(v)}</h3></article>`).join('')}<div class="mt-8">${link(t.payment.cta,r.payment)}</div></div></section>${visas(t)}${faq(t)}`}
function subhero(t,l,key,title,description){return `<section class="subhero"><div class="breadcrumb"><a href="${routes[l].home}">SAMANA South Haven 2</a><span>/</span><span>${e(key==='guide'?t.nav.invest:key==='payment'?t.footer.investment:key==='privacy'?t.footer.privacy:t.nav.residences)}</span></div><p class="eyebrow">DUBAI SOUTH · SAMANA SOUTH HAVEN 2</p><h1>${lines(title)}</h1><p>${e(description)}</p></section>`}
function pricing(t,l,i){let p=t.pricing;return `<div class="table-wrap">${i===0?`<table><caption class="sr-only">${e(p.title)}</caption><thead><tr><th>${e(p.floor)}</th><th>AED</th><th>USD ≈</th></tr></thead><tbody>${C.studioFloors.map(v=>`<tr><td>${e(p.floor)} ${v.floor}</td><td>${range(v.min,v.max,l)}</td><td>${range(v.min,v.max,l,'USD')}</td></tr>`).join('')}</tbody></table><p class="notice">${e(p.parkingStudio)}</p>`:i===2?`<table><tbody><tr><th>${e(p.range)}</th><td>${range(C.twoBed.min,C.twoBed.max,l)}<br>≈ ${range(C.twoBed.min,C.twoBed.max,l,'USD')}</td></tr><tr><th>${e(p.units)}</th><td>${C.twoBed.units.join(' · ')}</td></tr><tr><th>${e(p.area)}</th><td>≈ 1,059–1,085 sq. ft. / 98.4–100.8 m²</td></tr><tr><th>${e(p.communityView)}</th><td>${e(p.parkingTwo)}</td></tr></tbody></table>`:`<p>${e(t.ui.onRequest)}</p>`}</div><p class="notice">${e(p.usdNote)} ${e(p.availabilityNote)} ${e(p.sourceNote)}</p>`}
function residence(t,l,i){const v=t.residences.items[i],plans=i===0?['studio-plan']:i===1?['onebed-1-plan','onebed-2-plan','onebed-3-plan','onebed-4-plan']:['twobed-plan'];return `${subhero(t,l,'r'+i,v.name,v.description)}${pic(i===0?'living':i===1?'bedroom':'dining',t.alt.interior,false,'wide-image')}<section class="section wrap"><div class="split"><div><p class="eyebrow">${e(t.residences.eyebrow)}</p><h2>${e(t.pricing.title)}</h2><p class="body-copy">${e(t.residences.text)}</p>${btn(t.ui.requestPrice)}</div><div>${pricing(t,l,i)}</div></div></section><section class="wrap pb-20"><div class="feature-heading"><h2>${e(t.ui.requestPlans)}</h2><p>${e(t.ui.rendering)}</p></div><div class="plans">${plans.map((n,k)=>`<figure class="plan-card"><a href="/assets/${n}.webp" target="_blank" rel="noopener" aria-label="${e(t.ui.requestPlans)} ${k+1}"><img src="/assets/${n}.webp" alt="${e(t.alt[i===0?'studio':i===1?'oneBed':'twoBed'])} ${k+1}" width="2400" height="1697" loading="lazy"></a><figcaption>${e(v.name)}${plans.length>1?' · '+(k+1):''} ${arrow}</figcaption></figure>`).join('')}</div></section>${residences(t,l)}${faq(t)}`}
function guide(t,l){return `${subhero(t,l,'guide',t.guide.title,t.guide.eyebrow)}${pic('aerial',t.alt.architecture,false,'wide-image')}<article class="article">${t.guide.paragraphs.map((p,i)=>`<p>${e(p)}</p>${i===0?`<h2>${e(t.pricing.title)}</h2>${pricing(t,l,0)}`:''}`).join('')}${btn(t.guide.cta)}</article>${visas(t)}${faq(t)}`}
function payment(t,l){return `${subhero(t,l,'payment',t.payment.title,t.payment.text)}<article class="article"><div class="steps">${t.payment.steps.map((v,i)=>`<article><p class="eyebrow">0${i+1}</p><h3>${e(v)}</h3></article>`).join('')}</div><h2>${e(t.ui.studio)}</h2>${pricing(t,l,0)}<h2>${e(t.ui.twoBed)}</h2>${pricing(t,l,2)}<p>${e(t.ui.oneBed)}: ${e(t.ui.onRequest)}.</p>${btn(t.payment.cta)}</article>`}
function privacy(t,l){return `${subhero(t,l,'privacy',t.footer.privacy,t.footer.description)}<article class="article"><p>${e(t.footer.privacyText)}</p><h2>${e(t.footer.disclaimer)}</h2><p>${e(t.footer.disclaimerText)}</p><p>${e(t.visa.note)}</p><p>${e(t.pricing.usdNote)}</p><h2>${e(t.footer.sources)}</h2><p>${e(t.footer.brochureSource)}</p><p>Central Bank of the UAE · Dubai Land Department</p></article>`}
let all=[];for(const [l,t] of Object.entries(L))for(const key of Object.keys(routes[l])){const r=routes[l][key];const pageTitle=key==='home'?t.seo.title:`${(key==='guide'?t.guide.title:key==='payment'?t.payment.cta:key==='privacy'?t.footer.privacy:t.residences.items[+key.slice(1)].name).replaceAll('\n',' ')} | SAMANA South Haven 2`;
const description=key==='home'?t.seo.description:key==='guide'?t.guide.paragraphs[0].slice(0,170):key==='payment'?t.payment.text:key==='privacy'?t.footer.description:t.residences.items[+key.slice(1)].description;
const content=key==='home'?home(t,l):key==='guide'?guide(t,l):key==='payment'?payment(t,l):key==='privacy'?privacy(t,l):residence(t,l,+key.slice(1));
let schemas=[{'@context':'https://schema.org','@type':'WebPage',name:pageTitle,description,inLanguage:l,...(origin?{url:origin+r}:{})}];if(['home','guide','r0','r1','r2'].includes(key))schemas.push({'@context':'https://schema.org','@type':'FAQPage',mainEntity:t.faq.items.map(v=>({'@type':'Question',name:v.q,acceptedAnswer:{'@type':'Answer',text:v.a}}))});
const html=`<!doctype html><html lang="${l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(pageTitle)}</title><meta name="description" content="${e(description)}"><meta name="robots" content="${indexable?'index,follow,max-image-preview:large':'noindex,follow'}"><meta name="theme-color" content="#f4f1e9"><link rel="canonical" href="${origin+r}">${langs.map(x=>`<link rel="alternate" hreflang="${x}" href="${origin+routes[x][key]}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin+routes.en[key]}"><meta property="og:type" content="website"><meta property="og:title" content="${e(pageTitle)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${origin+r}"><meta property="og:image" content="${origin}/assets/hero.webp"><meta property="og:locale" content="${({en:'en_US',fr:'fr_FR',es:'es_ES',nl:'nl_NL',de:'de_DE',pt:'pt_PT'})[l]}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/styles.css"><script type="application/ld+json">${JSON.stringify(schemas).replaceAll('<','\\u003c')}</script><script src="/assets/app.js" defer></script></head><body>${header(l,key)}<main id="main">${content}${contact(t,l)}</main>${footer(t,l,key)}</body></html>`;
const file=path.join('dist',r,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,basePath?html.replace(/(href|src|value|srcset)="(\/[^"]*)"/g,(_,attribute,url)=>`${attribute}="${basePath}${url}"`):html);all.push({lang:l,key,path:r,title:pageTitle});}
fs.copyFileSync('src/app.js','dist/assets/app.js');fs.writeFileSync('dist/assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" fill="#333a2d"/><text x="32" y="47" font-size="46" fill="#f4f1e9" font-family="Georgia" text-anchor="middle">S</text></svg>');
fs.writeFileSync('dist/robots.txt',indexable?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
const xml=s=>e(s);fs.writeFileSync('dist/sitemap-pages.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${origin?all.map(v=>`<url><loc>${xml(origin+v.path)}</loc>${langs.map(l=>`<xhtml:link rel="alternate" hreflang="${l}" href="${xml(origin+routes[l][v.key])}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${xml(origin+routes.en[v.key])}"/></url>`).join(''):''}</urlset>`);
const imageEntries=origin?all.flatMap(v=>{
 const html=fs.readFileSync(path.join('dist',v.path,'index.html'),'utf8');
 const images=[...new Set([...html.matchAll(/<img[^>]*src="([^"]+\.webp)"/g)].map(m=>m[1]))];
 return images.length?[`<url><loc>${xml(origin+v.path)}</loc>${images.map(src=>`<image:image><image:loc>${xml(new URL(src,origin).href)}</image:loc></image:image>`).join('')}</url>`]:[];
}):[];
fs.writeFileSync('dist/sitemap-images.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">${imageEntries.join('')}</urlset>`);
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${origin?['sitemap-pages.xml','sitemap-images.xml'].map(file=>`<sitemap><loc>${xml(origin+'/'+file)}</loc></sitemap>`).join(''):''}</sitemapindex>`);
fs.writeFileSync('dist/404.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Page not found | SAMANA South Haven 2</title><meta name="robots" content="noindex,follow"><link rel="stylesheet" href="/assets/styles.css"><main class="subhero"><p>404</p><h1>Find your way home.</h1><a class="btn" href="/">SAMANA South Haven 2 ${arrow}</a></main></html>`);
if(basePath){const file='dist/404.html';fs.writeFileSync(file,fs.readFileSync(file,'utf8').replace(/(href|src)="(\/[^"]*)"/g,(_,a,u)=>`${a}="${basePath}${u}"`));}
fs.writeFileSync('routes.json',JSON.stringify(all,null,2));console.log(`Built ${all.length} pages in ${langs.length} languages. Origin: ${origin||'not configured; local preview'}. Indexable: ${indexable}`);
